{% set version = "1.0.1" %}
{% set sha256 = "388da53f32c3fc6d15f83dacb110afa697d85d14a4a50f2ab281221c830c691e" %}

package:
  name: exec-wrappers
  version: {{ version }}

source:
  fn: exec-wrappers-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/exec-wrappers/exec-wrappers-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - create-wrappers = exec_wrappers.create_wrappers:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - exec_wrappers
  commands:
    - create-wrappers --help

about:
  home: https://github.com/gqmelo/exec-wrappers
  license: MIT
  summary: 'command line tool to create wrappers around executables'

  description: |
    exec-wrappers is a command line tool to create wrappers around executable
    files that need to be executed on a particular environment (e.g. conda, virtualenv, schroot)
  doc_url: https://github.com/gqmelo/exec-wrappers
  dev_url: https://github.com/gqmelo/exec-wrappers

extra:
  recipe-maintainers:
    - gqmelo
